### ISSUE TITLE
Cannot build package on py27

### ISSUE THREAD

**Issue by nicoddemus** [conda-forge/pywin32-feedstock#10]
The py27 build is currently [failing](https://ci.appveyor.com/project/conda-forge/pywin32-feedstock/build/1.0.22/job/bqm8wi949hc49w04) with this message:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\bld\pywin32_1535373754503\_h_env\libs /LIBPATH:C:\bld\pywin32_1535373754503\_h_env\PCbuild\amd64 /LIBPATH:C:\bld\pywin32_1535373754503\_h_env\PC\VS9.0\amd64 /LIBPATH:build\temp.win-amd64-2.7\Release "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v7.0\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\lib\x64" advapi32.lib /EXPORT:OpenPerformanceData /EXPORT:CollectPerformanceData /EXPORT:ClosePerformanceData build\temp.win-amd64-2.7\Release\win32/src/PerfMon/PyPerfMsgs.res build\temp.win-amd64-2.7\Release\win32/src/PerfMon/perfmondata.obj /OUT:build\lib.win-amd64-2.7\win32\perfmondata.dll /IMPLIB:build\temp.win-amd64-2.7\Release\win32/src/PerfMon\perfmondata.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\win32/src/PerfMon\perfmondata.dll.manifest /MACHINE:amd64 /BASE:0x1e710000 /DEBUG /PDB:build\temp.win-amd64-2.7\Release\perfmondata.pdb
   Creating library build\temp.win-amd64-2.7\Release\win32/src/PerfMon\perfmondata.lib and object build\temp.win-amd64-2.7\Release\win32/src/PerfMon\perfmondata.exp
error: [Errno 2] No such file or directory: 'build\\temp.win-amd64-2.7\\Release\\win32/src/PerfMon\\perfmondata.dll.manifest'
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 415, in execute
    verify=args.verify)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2209, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1398, in build
    windows.build(m, build_file, stats=build_stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\windows.py", line 313, in build
    check_call_env(cmd, cwd=src_dir, stats=stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
Command exited with code 1
```

xref: #9

**Comment by mingwandroid** [comment]
Why are you using vs2014 to compile a python 2.7 module?

**Comment by nicoddemus** [comment]
Hi @mingwandroid, thanks for chipping in.

Here's how the build requirements are being set:

```yaml
requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
  run:
    - python
```

Is this incorrect?

**Comment by mingwandroid** [comment]
Should be ok.. seems our recipes are quite out of sync now though and we've done major work on pywin32 (I'd love to remove this package eventually, it serves little purpose now-a-days), anyway, here's where I'm at with it:

https://github.com/AnacondaRecipes/pywin32-feedstock/tree/master/recipe

**Comment by mingwandroid** [comment]
This is important w.r.t. ensuring the right compiler and SDK get used:

 https://github.com/AnacondaRecipes/pywin32-feedstock/blob/master/recipe/0002-ucrt-compatibility-fixes.patch

**Comment by mingwandroid** [comment]
But I don't recommend taking my fixes bit-part. Best to take them all.

**Comment by nicoddemus** [comment]
Thanks @mingwandroid for the tips.

@carlodri we talked about applying the patches from the AnacondaRecipes, but I don't see them in the PR, perhaps that's the missing bit?

**Comment by carlodri** [comment]
@nicoddemus you're right, sorry, I'm overwhelmed with work stuff so I didn't have the time to transfer the patches...

**Comment by carlodri** [comment]
py27 is no more built, closing
